network:
    ethernets:
        enp0s3:
            #Change to the wanted IP address for the MinIO host
            addresses: [192.168.1.3/24]
            #Change to the clients required gateway for this subnet
            gateway4: 192.168.1.1
            nameservers:
                #change to the clients required DNS servers
                addresses: [4.2.2.2, 8.8.8.8]
    version: 2